# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from dotaservice.protos import DotaService_pb2 as dotaservice_dot_protos_dot_DotaService__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in dotaservice/protos/DotaService_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DotaServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.reset = channel.unary_unary(
                '/DotaService/reset',
                request_serializer=dotaservice_dot_protos_dot_DotaService__pb2.GameConfig.SerializeToString,
                response_deserializer=dotaservice_dot_protos_dot_DotaService__pb2.InitialObservation.FromString,
                _registered_method=True)
        self.observe = channel.unary_unary(
                '/DotaService/observe',
                request_serializer=dotaservice_dot_protos_dot_DotaService__pb2.ObserveConfig.SerializeToString,
                response_deserializer=dotaservice_dot_protos_dot_DotaService__pb2.Observation.FromString,
                _registered_method=True)
        self.act = channel.unary_unary(
                '/DotaService/act',
                request_serializer=dotaservice_dot_protos_dot_DotaService__pb2.Actions.SerializeToString,
                response_deserializer=dotaservice_dot_protos_dot_DotaService__pb2.Empty.FromString,
                _registered_method=True)


class DotaServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def reset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def observe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def act(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DotaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'reset': grpc.unary_unary_rpc_method_handler(
                    servicer.reset,
                    request_deserializer=dotaservice_dot_protos_dot_DotaService__pb2.GameConfig.FromString,
                    response_serializer=dotaservice_dot_protos_dot_DotaService__pb2.InitialObservation.SerializeToString,
            ),
            'observe': grpc.unary_unary_rpc_method_handler(
                    servicer.observe,
                    request_deserializer=dotaservice_dot_protos_dot_DotaService__pb2.ObserveConfig.FromString,
                    response_serializer=dotaservice_dot_protos_dot_DotaService__pb2.Observation.SerializeToString,
            ),
            'act': grpc.unary_unary_rpc_method_handler(
                    servicer.act,
                    request_deserializer=dotaservice_dot_protos_dot_DotaService__pb2.Actions.FromString,
                    response_serializer=dotaservice_dot_protos_dot_DotaService__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DotaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('DotaService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DotaService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DotaService/reset',
            dotaservice_dot_protos_dot_DotaService__pb2.GameConfig.SerializeToString,
            dotaservice_dot_protos_dot_DotaService__pb2.InitialObservation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def observe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DotaService/observe',
            dotaservice_dot_protos_dot_DotaService__pb2.ObserveConfig.SerializeToString,
            dotaservice_dot_protos_dot_DotaService__pb2.Observation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def act(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DotaService/act',
            dotaservice_dot_protos_dot_DotaService__pb2.Actions.SerializeToString,
            dotaservice_dot_protos_dot_DotaService__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
