FROM dota:latest
MAINTAINER Tim Zaman <timbobel@gmail.com>

RUN apt-get -q update
RUN apt-get install -y python3.12
RUN curl -s https://bootstrap.pypa.io/get-pip.py -o /tmp/get-pip.py
RUN python3.12 /tmp/get-pip.py --break-system-packages
RUN python3.12 -m pip install --upgrade setuptools --break-system-packages

WORKDIR /root

RUN mkdir /root/dotaservice
COPY setup.py README.md /root/dotaservice/
COPY dotaservice /root/dotaservice/dotaservice/
RUN pip3.12 install --user -e /root/dotaservice/ --break-system-packages

ENV PYTHONPATH /root/dotaservice/

ENTRYPOINT ["python3.12", "-m", "dotaservice"]
